kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: registry.strecks.net/discord-bot-drone
    registry: https://registry.strecks.net
    auto_tag: true
    dockerfile: Dockerfile
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    environment:
      PLUGIN_DEBUG: true
- name: run
  image: docker:dind
  volume:
    - /var/run
  commands:
    - sleep 5
    - docker service update discord-bot