version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - net

  discordBot:
    image: node
    expose:
      - "3000"
    user: root
    working_dir: /discordBot/
    entrypoint:
      - npm
      - run
      - production
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"
    volumes:
      - .:/discordBot/
    networks:
      - net
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

volumes:
  mongodata:

networks:
  net:
